services:
  api:
    build: ./
    container_name: speech-api
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_REGION=us-east-1
      - S3_ENDPOINT=http://minio:9000
      - S3_BUCKET=diarization-files
      - HF_TOKEN=***
    volumes:
      - ./backend:/app
      - ./backend/models:/models
    depends_on:
      - minio
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 8
              capabilities: [gpu]

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # основной API
      - "9001:9001"   # веб-консоль
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./minio/data:/data
